# SPDX-License-Identifier: AGPL-3.0-only
"""GAP-PUBLIC-NODE-FIREWALL-00 firewall plan generator tests."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

import ilc_core.node.firewall_plan_runtime as firewall_plan_runtime
from ilc_core.node.firewall_plan_runtime import build_firewall_plan
from ilc_core.node.operator_init_runtime import generate_node_init_material


def _run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "ilc_core.cli", *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
        timeout=30,
    )


def _generated_config(tmp_path: Path) -> Path:
    result = generate_node_init_material(
        root=tmp_path / "node",
        network_id="ilc-rc01",
        host="203.0.113.10",
        grpc_port=50151,
        quic_port=7101,
        allow_test_stub_crypto=True,
    )
    return result.config_path


def _write_config(path: Path, *, grpc_endpoint: str = "203.0.113.10:50151", grpc_listen: str = "0.0.0.0:50151", p2p_listen: str = "0.0.0.0:7101", public_endpoint: str = "203.0.113.10:7101") -> Path:
    path.write_text(
        "\n".join(
            [
                "[network]",
                'network_id = "ilc-rc01"',
                "",
                "[grpc]",
                f'grpc_listen_addr = "{grpc_listen}"',
                "",
                "[p2p]",
                f'p2p_listen_addr = "{p2p_listen}"',
                f'public_endpoint = "{public_endpoint}"',
                "",
                "[validator]",
                f'grpc_endpoint = "{grpc_endpoint}"',
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


def _cli_payload(result: subprocess.CompletedProcess[str]) -> dict[str, object]:
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert isinstance(payload, dict)
    return payload


def _plan_output(payload: dict[str, object]) -> str:
    data = payload.get("data")
    assert isinstance(data, dict)
    output = data.get("output")
    assert isinstance(output, str)
    return output


def test_firewall_plan_help_discoverable() -> None:
    result = _run_cli("node", "firewall-plan", "--help")

    assert result.returncode == 0
    assert "--provider" in result.stdout
    assert "--source-mode" in result.stdout
    assert "--output" in result.stdout


def test_firewall_plan_generic_output(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    plan = build_firewall_plan(config_path=config_path, provider="generic")
    payload = json.loads(plan.output)

    assert payload["provider"] == "generic"
    assert {"port": 50151, "protocol": "tcp", "direction": "inbound", "purpose": "ilc-node gRPC ingress"} in payload["port_table"]
    assert {"port": 7101, "protocol": "udp", "direction": "inbound", "purpose": "ilc-node QUIC/P2P"} in payload["port_table"]


def test_firewall_plan_do_output_is_valid_json(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    plan = build_firewall_plan(config_path=config_path, provider="digitalocean")
    payload = json.loads(plan.output)

    assert payload["comment"] == "ilc-node firewall plan - generated by ilc node firewall-plan"
    assert isinstance(payload["inbound_rules"], list)
    assert payload["inbound_rules"]


def test_firewall_plan_do_output_tcp_port_matches_config(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="digitalocean").output)

    assert {
        "ports": "50151",
        "protocol": "tcp",
        "sources": {"addresses": ["0.0.0.0/0", "::/0"]},
    } in payload["inbound_rules"]


def test_firewall_plan_do_output_udp_port_matches_config(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="digitalocean").output)

    assert {
        "ports": "7101",
        "protocol": "udp",
        "sources": {"addresses": ["0.0.0.0/0", "::/0"]},
    } in payload["inbound_rules"]


def test_firewall_plan_uses_public_grpc_endpoint_port_when_mapped(tmp_path: Path) -> None:
    config_path = _write_config(
        tmp_path / "node_config.toml",
        grpc_endpoint="203.0.113.10:443",
        grpc_listen="0.0.0.0:50151",
    )

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="digitalocean").output)

    assert {
        "ports": "443",
        "protocol": "tcp",
        "sources": {"addresses": ["0.0.0.0/0", "::/0"]},
    } in payload["inbound_rules"]
    assert "nc -z -w 3 203.0.113.10 443" == payload["verification_hint"]
    assert payload["warnings"] == ["node_firewall_grpc_endpoint_port_differs_from_listen_port"]


def test_firewall_plan_ufw_output_contains_ufw_allow(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    output = build_firewall_plan(config_path=config_path, provider="ufw").output

    assert "sudo ufw allow 50151/tcp comment 'ilc-node gRPC ingress'" in output
    assert "sudo ufw allow 7101/udp comment 'ilc-node QUIC/P2P'" in output
    assert output.count("sudo ufw allow 50151/tcp") == 1
    assert output.count("sudo ufw allow 7101/udp") == 1


def test_firewall_plan_ufw_validator_set_restricts_sources(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    output = build_firewall_plan(
        config_path=config_path,
        provider="ufw",
        source_mode="validator-set",
        validator_ips="1.2.3.4,5.6.7.8",
    ).output

    assert "sudo ufw allow from 1.2.3.4 to any port 50151 proto tcp" in output
    assert "sudo ufw allow from 5.6.7.8 to any port 7101 proto udp" in output


def test_firewall_plan_ufw_controller_only_splits_sources(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    output = build_firewall_plan(
        config_path=config_path,
        provider="ufw",
        source_mode="controller-only",
        controller_ip="9.9.9.9",
        validator_ips="1.2.3.4",
    ).output

    assert "sudo ufw allow from 9.9.9.9 to any port 50151 proto tcp" in output
    assert "sudo ufw allow from 1.2.3.4 to any port 7101 proto udp" in output


def test_firewall_plan_includes_public_endpoint_extra_udp_port(tmp_path: Path) -> None:
    config_path = _write_config(
        tmp_path / "node_config.toml",
        p2p_listen="0.0.0.0:7101",
        public_endpoint="203.0.113.10:7201",
    )

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="generic").output)

    assert {"port": 7101, "protocol": "udp", "direction": "inbound", "purpose": "ilc-node QUIC/P2P"} in payload["port_table"]
    assert {"port": 7201, "protocol": "udp", "direction": "inbound", "purpose": "ilc-node QUIC/P2P public endpoint"} in payload["port_table"]


def test_firewall_plan_source_mode_validator_set_restricts_ips(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    payload = json.loads(
        build_firewall_plan(
            config_path=config_path,
            provider="digitalocean",
            source_mode="validator-set",
            validator_ips="1.2.3.4,5.6.7.8",
        ).output
    )

    assert payload["inbound_rules"][0]["sources"]["addresses"] == ["1.2.3.4", "5.6.7.8"]
    assert payload["inbound_rules"][1]["sources"]["addresses"] == ["1.2.3.4", "5.6.7.8"]


def test_firewall_plan_controller_only_splits_tcp_and_udp_sources(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    payload = json.loads(
        build_firewall_plan(
            config_path=config_path,
            provider="digitalocean",
            source_mode="controller-only",
            controller_ip="9.9.9.9",
            validator_ips="1.2.3.4",
        ).output
    )

    by_protocol = {rule["protocol"]: rule["sources"]["addresses"] for rule in payload["inbound_rules"]}
    assert by_protocol["tcp"] == ["9.9.9.9"]
    assert by_protocol["udp"] == ["1.2.3.4"]


def test_firewall_plan_source_modes_require_ips(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    with pytest.raises(ValueError, match="node_firewall_validator_ips_required"):
        build_firewall_plan(config_path=config_path, source_mode="validator-set")

    with pytest.raises(ValueError, match="node_firewall_controller_ip_required"):
        build_firewall_plan(config_path=config_path, source_mode="controller-only", validator_ips="1.2.3.4")


def test_firewall_plan_missing_config_and_sections_fail(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="node_firewall_config_missing"):
        build_firewall_plan(config_path=tmp_path / "missing.toml")

    config_path = tmp_path / "node_config.toml"
    config_path.write_text('[network]\nnetwork_id = "ilc-rc01"\n', encoding="utf-8")
    with pytest.raises(ValueError, match="node_firewall_grpc_section_missing"):
        build_firewall_plan(config_path=config_path)


def test_firewall_plan_rejects_oversized_config(tmp_path: Path) -> None:
    config_path = tmp_path / "node_config.toml"
    config_path.write_text("#" * (firewall_plan_runtime.MAX_NODE_CONFIG_BYTES + 1), encoding="utf-8")

    with pytest.raises(ValueError, match="node_firewall_config_too_large"):
        build_firewall_plan(config_path=config_path)


def test_firewall_plan_ipv6_hint_uses_unbracketed_host(tmp_path: Path) -> None:
    config_path = _write_config(
        tmp_path / "node_config.toml",
        grpc_endpoint="[2001:db8::1]:50151",
        public_endpoint="[2001:db8::1]:7101",
    )

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="generic").output)

    assert payload["verification_hint"] == "nc -z -w 3 2001:db8::1 50151"


def test_firewall_plan_advisory_present_in_all_formats(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    for provider in ("digitalocean", "generic", "ufw"):
        output = build_firewall_plan(config_path=config_path, provider=provider).output
        assert "gRPC is mTLS-authenticated" in output
        assert "Peer-authenticated proposal ingress" in output
        assert "nc -z -w 3 203.0.113.10 50151" in output
        assert "HTTP/2 over TCP fallback" in output or "HTTP/2 TCP fallback" in output


def test_firewall_plan_output_written_atomically(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)
    output_path = tmp_path / "plans" / "firewall.json"

    result = _run_cli(
        "node",
        "firewall-plan",
        "--config",
        str(config_path),
        "--provider",
        "digitalocean",
        "--output",
        str(output_path),
    )

    payload = _cli_payload(result)
    data = payload["data"]
    assert isinstance(data, dict)
    assert data["wrote_output_path"] == str(output_path)
    assert output_path.is_file()
    assert json.loads(output_path.read_text(encoding="utf-8"))["inbound_rules"]
    assert list(output_path.parent.glob("*.tmp")) == []


def test_firewall_plan_cli_generic_json_first(tmp_path: Path) -> None:
    config_path = _generated_config(tmp_path)

    result = _run_cli("node", "firewall-plan", "--config", str(config_path))
    payload = _cli_payload(result)

    assert payload["command"] == "node firewall-plan"
    assert payload["ok"] is True
    output = _plan_output(payload)
    assert json.loads(output)["provider"] == "generic"


def test_firewall_plan_tomllib_fallback_parses_generated_config(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    config_path = _generated_config(tmp_path)

    monkeypatch.setattr(firewall_plan_runtime, "tomllib", None)

    payload = json.loads(build_firewall_plan(config_path=config_path, provider="generic").output)

    assert payload["network_id"] == "ilc-rc01"
    assert {"port": 50151, "protocol": "tcp", "direction": "inbound", "purpose": "ilc-node gRPC ingress"} in payload["port_table"]


def test_firewall_plan_tomllib_fallback_rejects_malformed_value(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    config_path = tmp_path / "node_config.toml"
    config_path.write_text('[network]\nnetwork_id = "unterminated\n', encoding="utf-8")
    monkeypatch.setattr(firewall_plan_runtime, "tomllib", None)

    with pytest.raises(ValueError, match="node_firewall_config_invalid_toml"):
        build_firewall_plan(config_path=config_path, provider="generic")


def test_firewall_plan_no_network_or_subprocess_imports() -> None:
    source = Path("ilc_core/node/firewall_plan_runtime.py").read_text(encoding="utf-8")

    assert "subprocess" not in source
    assert "requests" not in source
    assert "urllib.request" not in source
    assert "socket" not in source
