"""CDL-V3/V7 consensus runtime package."""

from .circuit_breaker_interface import (
    CDL_045_DEPENDENCY,
    CIRCUIT_BREAKER_INTERFACE_VERSION,
    CircuitBreakerInterfaceError,
    build_circuit_breaker_request,
    summarize_circuit_breaker_quorum_state,
    verify_circuit_breaker_request,
)
from .diversity_floor_runtime import (
    CDL_V2_DEPENDENCY,
    CDL_V3_DEPENDENCY,
    CDL_V3_RUNTIME_VERSION,
    DiversityFloorValidationError,
    compute_diversity_floor_penalty,
    compute_max_cluster_share,
    meets_distinct_cluster_floor,
    meets_max_cluster_share_ceiling,
)
from .finality_evaluator import (
    CDL_051_RATIFICATION_DEPENDENCY,
    DIVERSITY_AWARE_FINALITY_VERSION,
    FINALITY_EVALUATOR_VERSION,
    ConsensusFinalityEvaluatorError,
    evaluate_epoch_finality,
    evaluate_epoch_finality_with_diversity,
    resolve_fork,
)
from .popperian_gate_runtime import (
    CDL_V7_DEPENDENCY,
    CDL_V7_RUNTIME_VERSION,
    PopperianGateValidationError,
    evaluate_decomposition_admissibility,
    is_claim_form_admissible,
    meets_reproducibility_threshold,
    passes_falsifiability_gate,
    reject_inadmissible_counterexample,
)

__all__ = [
    "CDL_045_DEPENDENCY",
    "CDL_051_RATIFICATION_DEPENDENCY",
    "CDL_V2_DEPENDENCY",
    "CDL_V3_RUNTIME_VERSION",
    "CDL_V3_DEPENDENCY",
    "CDL_V7_RUNTIME_VERSION",
    "CDL_V7_DEPENDENCY",
    "CIRCUIT_BREAKER_INTERFACE_VERSION",
    "DIVERSITY_AWARE_FINALITY_VERSION",
    "FINALITY_EVALUATOR_VERSION",
    "DiversityFloorValidationError",
    "CircuitBreakerInterfaceError",
    "ConsensusFinalityEvaluatorError",
    "PopperianGateValidationError",
    "build_circuit_breaker_request",
    "summarize_circuit_breaker_quorum_state",
    "verify_circuit_breaker_request",
    "compute_max_cluster_share",
    "meets_distinct_cluster_floor",
    "meets_max_cluster_share_ceiling",
    "compute_diversity_floor_penalty",
    "evaluate_epoch_finality",
    "evaluate_epoch_finality_with_diversity",
    "resolve_fork",
    "is_claim_form_admissible",
    "passes_falsifiability_gate",
    "reject_inadmissible_counterexample",
    "meets_reproducibility_threshold",
    "evaluate_decomposition_admissibility",
]
