/// pq_agent_sign_main.rs — Phase 1568 Fix2b-2: agent submission ML-DSA-65 signing tool.
///
/// Signs agent submission payloads with a domain-separated context distinct from the
/// Genesis root envelope signing context. Each of the 7 rehearsal agents has a
/// committed mldsa_pk_hex in the Phase 1431 identity manifest; this tool verifies the
/// derived public key matches that manifest record before emitting any signature.
///
/// SECURITY CONTRACT:
/// - Secret mldsa seed material is read from stdin only.
/// - Secret mldsa seed material is never accepted as a CLI argument.
/// - Secret mldsa seed material is never written to disk.
/// - The derived public key must match the agent's committed mldsa_pk_hex in the
///   Phase 1431 manifest before any signature is emitted.
/// - Signing context ILC_AGENT_SUBMISSION_V1 is domain-separated from
///   ILC_GENESIS_ROOT_ENVELOPE_V1 used by pq_sign. Do not conflate the two.
///
/// The mldsa_seed is the ML-DSA seed generated by pq_keygen (separate from the
/// identity_seed from which agent_id is derived). These are distinct 32-byte values.
///
/// Usage:
///   pq_agent_sign --agent-id <agent_id_hex> --input-file <path>
///   pq_agent_sign verify --agent-id <agent_id_hex> --input-file <path> --signature-hex <hex>
///   pq_agent_sign [--manifest <path>]
///     (default manifest: docs/specs/ilc_rehearsal_agent_identity_manifest_1431_v0.1.md)
///
/// `pq_agent_sign_1568_fix2b2_binary_present`
use std::collections::{BTreeMap, HashSet};
use std::fs::{self, File};
use std::io::{self, Read};
use std::path::{Path, PathBuf};

use bip39::Mnemonic;
use fips204::ml_dsa_65;
use fips204::traits::{KeyGen, SerDes as MldsaSerDes, Signer, Verifier};
use getrandom::getrandom;
use sha2::{Digest, Sha256};
use zeroize::Zeroize;

const SIGNING_CONTEXT: &[u8] = b"ILC_AGENT_SUBMISSION_V1";
const DEFAULT_MANIFEST: &str = "docs/specs/ilc_rehearsal_agent_identity_manifest_1431_v0.1.md";
const AGENT_ID_HEX_LEN: usize = 48 * 2;
const MLDSA_PUBLIC_KEY_HEX_LEN: usize = 1952 * 2;
const MLDSA_SIGNATURE_HEX_LEN: usize = 3309 * 2;
const MAX_SIGN_INPUT_BYTES: usize = 4 * 1024 * 1024;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let result = match parse_args(&args) {
        Command::Sign {
            agent_id,
            input_file,
            manifest,
            envelope_json,
        } => sign_command(&agent_id, &input_file, &manifest, envelope_json),
        Command::Verify {
            agent_id,
            input_file,
            manifest,
            signature_hex,
        } => verify_command(&agent_id, &input_file, &manifest, &signature_hex),
        Command::Help => {
            print_usage();
            Ok(())
        }
    };
    if let Err(err) = result {
        eprintln!("{err}");
        std::process::exit(1);
    }
}

enum Command {
    Sign {
        agent_id: String,
        input_file: PathBuf,
        manifest: PathBuf,
        envelope_json: bool,
    },
    Verify {
        agent_id: String,
        input_file: PathBuf,
        manifest: PathBuf,
        signature_hex: String,
    },
    Help,
}

fn parse_args(args: &[String]) -> Command {
    if args.iter().any(|arg| arg == "--help" || arg == "-h") {
        return Command::Help;
    }
    let mut idx = 1;
    let mut mode = "sign";
    if args.get(idx).is_some_and(|arg| arg == "verify") {
        mode = "verify";
        idx += 1;
    }
    let mut agent_id: Option<String> = None;
    let mut input_file: Option<PathBuf> = None;
    let mut manifest = default_manifest_path();
    let mut signature_hex: Option<String> = None;
    let mut envelope_json = false;
    while idx < args.len() {
        match args[idx].as_str() {
            "--agent-id" => {
                idx += 1;
                let Some(id) = args.get(idx) else {
                    fail("--agent-id requires a value");
                };
                agent_id = Some(id.clone());
            }
            "--input-file" => {
                idx += 1;
                let Some(path) = args.get(idx) else {
                    fail("--input-file requires a path");
                };
                input_file = Some(PathBuf::from(path));
            }
            "--manifest" => {
                idx += 1;
                let Some(path) = args.get(idx) else {
                    fail("--manifest requires a path");
                };
                manifest = PathBuf::from(path);
            }
            "--signature-hex" => {
                idx += 1;
                let Some(sig) = args.get(idx) else {
                    fail("--signature-hex requires a value");
                };
                signature_hex = Some(sig.clone());
            }
            "--envelope-json" => {
                envelope_json = true;
            }
            "--seed" | "--seed-hex" | "--mnemonic" => {
                fail("secret mldsa seed material must be provided via stdin, not CLI args");
            }
            other => {
                fail(&format!("unknown argument: {other}"));
            }
        }
        idx += 1;
    }
    let Some(agent_id) = agent_id else {
        fail("--agent-id is required");
    };
    let Some(input_file) = input_file else {
        fail("--input-file is required");
    };
    match mode {
        "sign" => {
            if signature_hex.is_some() {
                fail("--signature-hex is only valid in verify mode");
            }
            Command::Sign {
                agent_id,
                input_file,
                manifest,
                envelope_json,
            }
        }
        "verify" => {
            if envelope_json {
                fail("--envelope-json is only valid in sign mode");
            }
            let Some(signature_hex) = signature_hex else {
                fail("verify requires --signature-hex");
            };
            Command::Verify {
                agent_id,
                input_file,
                manifest,
                signature_hex,
            }
        }
        _ => unreachable!(),
    }
}

fn sign_command(
    agent_id: &str,
    input_file: &PathBuf,
    manifest: &PathBuf,
    envelope_json: bool,
) -> Result<(), String> {
    let normalized_agent_id = normalize_agent_id_hex(agent_id)?;
    let expected_pk_hex = read_agent_mldsa_pk_hex(manifest, agent_id)?;
    eprintln!(
        "Enter ML-DSA-65 mldsa_seed for agent {}... as 24 BIP-39 words or 64-char hex, then press Ctrl-D:",
        truncate_agent_id(&normalized_agent_id),
    );
    let mut seed = read_seed_from_stdin()?;
    let keypair = ml_dsa_65::KG::try_keygen_with_rng(&mut SeedRng::new(&seed));
    seed.zeroize();
    let (pk, sk) = keypair.map_err(|err| format!("ML-DSA-65 key derivation failed: {err}"))?;
    let derived_pk_hex = hex_encode(&pk.clone().into_bytes());
    if derived_pk_hex != expected_pk_hex {
        return Err("derived_mldsa_public_key_does_not_match_manifest_record".to_string());
    }
    let message = read_bounded_file(input_file)?;
    let sig = sk
        .try_sign_with_rng(&mut OsRandom, &message, SIGNING_CONTEXT)
        .map_err(|err| format!("ML-DSA-65 signing failed: {err}"))?;
    let signature_hex = hex_encode(&sig);
    if envelope_json {
        println!(
            "{}",
            signature_envelope_json(
                &normalized_agent_id,
                input_file,
                manifest,
                &message,
                &signature_hex,
            )?
        );
    } else {
        println!("{signature_hex}");
    }
    Ok(())
}

fn verify_command(
    agent_id: &str,
    input_file: &PathBuf,
    manifest: &PathBuf,
    signature_hex: &str,
) -> Result<(), String> {
    let pk_hex = read_agent_mldsa_pk_hex(manifest, agent_id)?;
    let pk_bytes_vec = hex_decode(&pk_hex)?;
    let pk_bytes: [u8; 1952] = pk_bytes_vec
        .try_into()
        .map_err(|_| "mldsa_public_key_wrong_length".to_string())?;
    let pk = ml_dsa_65::PublicKey::try_from_bytes(pk_bytes)
        .map_err(|err| format!("ML-DSA-65 public key parse failed: {err}"))?;
    let signature_hex = normalize_signature_hex(signature_hex)?;
    let sig_vec = hex_decode(&signature_hex)?;
    let sig: [u8; 3309] = sig_vec
        .try_into()
        .map_err(|_| "mldsa_agent_submission_signature_wrong_length".to_string())?;
    let message = read_bounded_file(input_file)?;
    if !pk.verify(&message, &sig, SIGNING_CONTEXT) {
        return Err("mldsa_agent_submission_signature_verification_failed".to_string());
    }
    println!("agent_submission_signature_verified");
    Ok(())
}

/// Parse the Phase 1431 rehearsal identity manifest (markdown with code blocks)
/// and return the mldsa_pk_hex for the given agent_id.
///
/// The manifest contains per-agent sections, each with a fenced code block (```)
/// containing `key: value` lines including `agent_id` and `mldsa_pk_hex`.
/// We find the block whose `agent_id` matches the target and return its `mldsa_pk_hex`.
///
/// Case-insensitive comparison on agent_id (all-lowercase SHA-384 hex expected).
fn read_agent_mldsa_pk_hex(
    manifest_path: &PathBuf,
    target_agent_id: &str,
) -> Result<String, String> {
    let text =
        fs::read_to_string(manifest_path).map_err(|err| format!("cannot read manifest: {err}"))?;
    let target = normalize_agent_id_hex(target_agent_id)?;
    let mut in_block = false;
    let mut block_agent_id: Option<String> = None;
    let mut block_mldsa_pk: Option<String> = None;
    let mut records: Vec<(String, String)> = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("```") {
            if in_block {
                if let (Some(aid), Some(pk)) = (&block_agent_id, &block_mldsa_pk) {
                    records.push((aid.clone(), pk.clone()));
                }
                block_agent_id = None;
                block_mldsa_pk = None;
                in_block = false;
            } else {
                in_block = true;
            }
            continue;
        }
        if !in_block {
            continue;
        }
        // Parse key: value within the code block; split on first ':' only
        if let Some((key, value)) = line.split_once(':') {
            let k = key.trim();
            let v = value.trim().to_string();
            if v.is_empty() {
                continue;
            }
            match k {
                "agent_id" => {
                    block_agent_id = Some(v);
                }
                "mldsa_pk_hex" => {
                    block_mldsa_pk = Some(v);
                }
                _ => {}
            }
        }
    }
    // Check the last block (if file doesn't end with ```)
    if in_block {
        if let (Some(aid), Some(pk)) = (&block_agent_id, &block_mldsa_pk) {
            records.push((aid.clone(), pk.clone()));
        }
    }
    let mut seen = HashSet::new();
    let mut match_pk: Option<String> = None;
    for (agent_id, pk_hex) in records {
        let agent_id = normalize_agent_id_hex(&agent_id)?;
        let pk_hex = normalize_mldsa_public_key_hex(&pk_hex)?;
        if !seen.insert(agent_id.clone()) {
            return Err(format!(
                "duplicate_agent_id_in_manifest:{}",
                truncate_agent_id(&agent_id),
            ));
        }
        if agent_id == target {
            match_pk = Some(pk_hex);
        }
    }
    match_pk.ok_or_else(|| {
        format!(
            "agent_id_not_found_in_manifest:{}",
            truncate_agent_id(&target),
        )
    })
}

fn truncate_agent_id(id: &str) -> String {
    id.chars().take(8).collect()
}

fn normalize_agent_id_hex(input: &str) -> Result<String, String> {
    normalize_hex_exact(
        input,
        AGENT_ID_HEX_LEN,
        "agent_id_wrong_length",
        "agent_id_must_be_hex",
    )
}

fn normalize_mldsa_public_key_hex(input: &str) -> Result<String, String> {
    normalize_hex_exact(
        input,
        MLDSA_PUBLIC_KEY_HEX_LEN,
        "mldsa_public_key_wrong_length",
        "mldsa_public_key_must_be_hex",
    )
}

fn normalize_signature_hex(input: &str) -> Result<String, String> {
    normalize_hex_exact(
        input,
        MLDSA_SIGNATURE_HEX_LEN,
        "mldsa_agent_submission_signature_wrong_length",
        "mldsa_agent_submission_signature_must_be_hex",
    )
}

fn normalize_hex_exact(
    input: &str,
    expected_len: usize,
    length_token: &str,
    hex_token: &str,
) -> Result<String, String> {
    let value = input.trim();
    if value.len() != expected_len {
        return Err(length_token.to_string());
    }
    if !value.as_bytes().iter().all(u8::is_ascii_hexdigit) {
        return Err(hex_token.to_string());
    }
    Ok(value.to_ascii_lowercase())
}

fn read_bounded_file(path: &Path) -> Result<Vec<u8>, String> {
    let metadata = fs::metadata(path).map_err(|err| format!("cannot stat input file: {err}"))?;
    if metadata.len() > MAX_SIGN_INPUT_BYTES as u64 {
        return Err(format!(
            "input_file_exceeds_max_bytes:{MAX_SIGN_INPUT_BYTES}"
        ));
    }
    let mut file = File::open(path).map_err(|err| format!("cannot read input file: {err}"))?;
    let mut reader = (&mut file).take((MAX_SIGN_INPUT_BYTES + 1) as u64);
    let mut out = Vec::new();
    reader
        .read_to_end(&mut out)
        .map_err(|err| format!("cannot read input file: {err}"))?;
    if out.len() > MAX_SIGN_INPUT_BYTES {
        return Err(format!(
            "input_file_exceeds_max_bytes:{MAX_SIGN_INPUT_BYTES}"
        ));
    }
    Ok(out)
}

fn signature_envelope_json(
    agent_id: &str,
    input_file: &Path,
    manifest: &Path,
    message: &[u8],
    signature_hex: &str,
) -> Result<String, String> {
    let manifest_bytes =
        fs::read(manifest).map_err(|err| format!("cannot read manifest: {err}"))?;
    let mut envelope = BTreeMap::new();
    envelope.insert("agent_id".to_string(), agent_id.to_string());
    envelope.insert("algorithm".to_string(), "ML-DSA-65".to_string());
    envelope.insert(
        "input_path".to_string(),
        input_file.to_string_lossy().to_string(),
    );
    envelope.insert("input_sha256".to_string(), sha256_hex(message));
    envelope.insert(
        "manifest_path".to_string(),
        manifest.to_string_lossy().to_string(),
    );
    envelope.insert("manifest_sha256".to_string(), sha256_hex(&manifest_bytes));
    envelope.insert("signature_hex".to_string(), signature_hex.to_string());
    envelope.insert(
        "signing_context".to_string(),
        String::from_utf8(SIGNING_CONTEXT.to_vec())
            .map_err(|err| format!("invalid signing context utf8: {err}"))?,
    );
    serde_json::to_string(&envelope)
        .map_err(|err| format!("agent_submission_signature_envelope_json_failed: {err}"))
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    hex_encode(&digest)
}

fn default_manifest_path() -> PathBuf {
    if let Some(path) = std::env::var_os("ILC_AGENT_SIGN_MANIFEST") {
        return PathBuf::from(path);
    }
    let default = PathBuf::from(DEFAULT_MANIFEST);
    if default.exists() {
        return default;
    }
    if let Ok(current_dir) = std::env::current_dir() {
        for ancestor in current_dir.ancestors() {
            let candidate = ancestor.join(DEFAULT_MANIFEST);
            if candidate.exists() {
                return candidate;
            }
        }
    }
    if let Ok(current_exe) = std::env::current_exe() {
        if let Some(parent) = current_exe.parent() {
            for ancestor in parent.ancestors() {
                let candidate = ancestor.join(DEFAULT_MANIFEST);
                if candidate.exists() {
                    return candidate;
                }
            }
        }
    }
    default
}

fn read_seed_from_stdin() -> Result<[u8; 32], String> {
    let mut input = String::new();
    io::stdin()
        .read_to_string(&mut input)
        .map_err(|err| format!("cannot read stdin: {err}"))?;
    let seed = parse_seed(input.trim());
    input.zeroize();
    seed
}

fn parse_seed(input: &str) -> Result<[u8; 32], String> {
    if input.split_whitespace().count() == 24 {
        let mnemonic =
            Mnemonic::parse(input).map_err(|err| format!("invalid BIP-39 mnemonic: {err}"))?;
        let entropy = mnemonic.to_entropy();
        return entropy
            .try_into()
            .map_err(|_| "mnemonic_entropy_must_be_32_bytes".to_string());
    }
    let bytes = hex_decode(input)?;
    bytes
        .try_into()
        .map_err(|_| "hex_seed_must_be_32_bytes".to_string())
}

fn hex_decode(input: &str) -> Result<Vec<u8>, String> {
    let input = input.trim();
    if input.len() % 2 != 0 {
        return Err("hex_input_odd_length".to_string());
    }
    let mut out = Vec::with_capacity(input.len() / 2);
    let bytes = input.as_bytes();
    let mut idx = 0;
    while idx < bytes.len() {
        let hi = hex_value(bytes[idx])?;
        let lo = hex_value(bytes[idx + 1])?;
        out.push((hi << 4) | lo);
        idx += 2;
    }
    Ok(out)
}

fn hex_value(byte: u8) -> Result<u8, String> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err("invalid_hex_character".to_string()),
    }
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{:02x}", byte)).collect()
}

fn print_usage() {
    eprintln!("Usage:");
    eprintln!("  pq_agent_sign --agent-id <agent_id_hex> --input-file <path> [--envelope-json]");
    eprintln!(
        "  pq_agent_sign verify --agent-id <agent_id_hex> --input-file <path> --signature-hex <hex>"
    );
    eprintln!("  [--manifest <path>]  (default: {DEFAULT_MANIFEST})");
    eprintln!("Secret mldsa seed material is read from stdin only.");
    eprintln!("Input files are bounded to {MAX_SIGN_INPUT_BYTES} bytes.");
    eprintln!("Signing context: ILC_AGENT_SUBMISSION_V1");
    eprintln!("mldsa_seed is distinct from identity_seed (CDL-069 agent_id derivation).");
}

fn fail(message: &str) -> ! {
    eprintln!("{message}");
    std::process::exit(1);
}

// ---------------------------------------------------------------------------
// RNG wrappers
// ---------------------------------------------------------------------------

struct OsRandom;

impl rand_core::RngCore for OsRandom {
    fn next_u32(&mut self) -> u32 {
        let mut buf = [0u8; 4];
        self.fill_bytes(&mut buf);
        u32::from_be_bytes(buf)
    }

    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.fill_bytes(&mut buf);
        u64::from_be_bytes(buf)
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        getrandom(dest).expect("getrandom failed");
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        getrandom(dest).map_err(rand_core::Error::new)
    }
}

impl rand_core::CryptoRng for OsRandom {}

/// Deterministic RNG matching Phase 838a pq_keygen key derivation.
///
/// The Phase 1431 manifest public keys were generated with pq_keygen_838a.v0.1,
/// which uses this SeedRng wrapper. Any change to this implementation would
/// produce a different public key and break the manifest cross-check.
/// Do not replace with `keygen_from_seed()` or any other derivation.
struct SeedRng {
    seed: [u8; 32],
    counter: u64,
    buffer: [u8; 48],
    pos: usize,
}

impl SeedRng {
    fn new(seed: &[u8; 32]) -> Self {
        let mut rng = SeedRng {
            seed: *seed,
            counter: 0,
            buffer: [0u8; 48],
            pos: 48,
        };
        rng.refill();
        rng
    }

    fn refill(&mut self) {
        let counter_bytes = self.counter.to_be_bytes();
        self.buffer = sha2_384(&[&self.seed, &counter_bytes]);
        self.counter += 1;
        self.pos = 0;
    }
}

impl rand_core::RngCore for SeedRng {
    fn next_u32(&mut self) -> u32 {
        let mut buf = [0u8; 4];
        self.fill_bytes(&mut buf);
        u32::from_be_bytes(buf)
    }

    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.fill_bytes(&mut buf);
        u64::from_be_bytes(buf)
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        let mut written = 0;
        while written < dest.len() {
            if self.pos >= self.buffer.len() {
                self.refill();
            }
            let available = self.buffer.len() - self.pos;
            let needed = dest.len() - written;
            let n = available.min(needed);
            dest[written..written + n].copy_from_slice(&self.buffer[self.pos..self.pos + n]);
            self.pos += n;
            written += n;
        }
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl rand_core::CryptoRng for SeedRng {}

// ---------------------------------------------------------------------------
// SHA-384 — inline implementation matching pq_sign_main.rs exactly.
// ---------------------------------------------------------------------------

fn sha2_384(parts: &[&[u8]]) -> [u8; 48] {
    const H0: [u64; 8] = [
        0xcbbb9d5dc1059ed8,
        0x629a292a367cd507,
        0x9159015a3070dd17,
        0x152fecd8f70e5939,
        0x67332667ffc00b31,
        0x8eb44a8768581511,
        0xdb0c2e0d64f98fa7,
        0x47b5481dbefa4fa4,
    ];
    const K: [u64; 80] = [
        0x428a2f98d728ae22,
        0x7137449123ef65cd,
        0xb5c0fbcfec4d3b2f,
        0xe9b5dba58189dbbc,
        0x3956c25bf348b538,
        0x59f111f1b605d019,
        0x923f82a4af194f9b,
        0xab1c5ed5da6d8118,
        0xd807aa98a3030242,
        0x12835b0145706fbe,
        0x243185be4ee4b28c,
        0x550c7dc3d5ffb4e2,
        0x72be5d74f27b896f,
        0x80deb1fe3b1696b1,
        0x9bdc06a725c71235,
        0xc19bf174cf692694,
        0xe49b69c19ef14ad2,
        0xefbe4786384f25e3,
        0x0fc19dc68b8cd5b5,
        0x240ca1cc77ac9c65,
        0x2de92c6f592b0275,
        0x4a7484aa6ea6e483,
        0x5cb0a9dcbd41fbd4,
        0x76f988da831153b5,
        0x983e5152ee66dfab,
        0xa831c66d2db43210,
        0xb00327c898fb213f,
        0xbf597fc7beef0ee4,
        0xc6e00bf33da88fc2,
        0xd5a79147930aa725,
        0x06ca6351e003826f,
        0x142929670a0e6e70,
        0x27b70a8546d22ffc,
        0x2e1b21385c26c926,
        0x4d2c6dfc5ac42aed,
        0x53380d139d95b3df,
        0x650a73548baf63de,
        0x766a0abb3c77b2a8,
        0x81c2c92e47edaee6,
        0x92722c851482353b,
        0xa2bfe8a14cf10364,
        0xa81a664bbc423001,
        0xc24b8b70d0f89791,
        0xc76c51a30654be30,
        0xd192e819d6ef5218,
        0xd69906245565a910,
        0xf40e35855771202a,
        0x106aa07032bbd1b8,
        0x19a4c116b8d2d0c8,
        0x1e376c085141ab53,
        0x2748774cdf8eeb99,
        0x34b0bcb5e19b48a8,
        0x391c0cb3c5c95a63,
        0x4ed8aa4ae3418acb,
        0x5b9cca4f7763e373,
        0x682e6ff3d6b2b8a3,
        0x748f82ee5defb2fc,
        0x78a5636f43172f60,
        0x84c87814a1f0ab72,
        0x8cc702081a6439ec,
        0x90befffa23631e28,
        0xa4506cebde82bde9,
        0xbef9a3f7b2c67915,
        0xc67178f2e372532b,
        0xca273eceea26619c,
        0xd186b8c721c0c207,
        0xeada7dd6cde0eb1e,
        0xf57d4f7fee6ed178,
        0x06f067aa72176fba,
        0x0a637dc5a2c898a6,
        0x113f9804bef90dae,
        0x1b710b35131c471b,
        0x28db77f523047d84,
        0x32caab7b40c72493,
        0x3c9ebe0a15c9bebc,
        0x431d67c49c100d4c,
        0x4cc5d4becb3e42b6,
        0x597f299cfc657e2a,
        0x5fcb6fab3ad6faec,
        0x6c44198c4a475817,
    ];
    let mut data: Vec<u8> = Vec::new();
    for part in parts {
        data.extend_from_slice(part);
    }
    let bit_len = data.len() as u128 * 8;
    data.push(0x80);
    while (data.len() % 128) != 112 {
        data.push(0x00);
    }
    data.extend_from_slice(&bit_len.to_be_bytes());

    let mut h = H0;
    for block in data.chunks(128) {
        let mut w = [0u64; 80];
        for i in 0..16 {
            let b = &block[i * 8..(i + 1) * 8];
            w[i] = u64::from_be_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]);
        }
        for i in 16..80 {
            let s0 = w[i - 15].rotate_right(1) ^ w[i - 15].rotate_right(8) ^ (w[i - 15] >> 7);
            let s1 = w[i - 2].rotate_right(19) ^ w[i - 2].rotate_right(61) ^ (w[i - 2] >> 6);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..80 {
            let s1 = e.rotate_right(14) ^ e.rotate_right(18) ^ e.rotate_right(41);
            let ch = (e & f) ^ ((!e) & g);
            let temp1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(28) ^ a.rotate_right(34) ^ a.rotate_right(39);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(temp1);
            d = c;
            c = b;
            b = a;
            a = temp1.wrapping_add(temp2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }

    let mut out = [0u8; 48];
    for (i, word) in h[..6].iter().enumerate() {
        out[i * 8..(i + 1) * 8].copy_from_slice(&word.to_be_bytes());
    }
    out
}
