# SPDX-License-Identifier: AGPL-3.0-only
"""Phase 1444 CLA governance status tokens."""

from __future__ import annotations

CLA_TEXT_FINALIZED_PHASE_1444_TOKEN: str = "cla_text_finalized_phase_1444"
CLA_GOVERNANCE_POLICY_COMMITTED_PHASE_1444_TOKEN: str = (
    "cla_governance_policy_committed_phase_1444"
)
CLA_NOT_EXTERNAL_LEGAL_OPINION_PHASE_1444_TOKEN: str = (
    "cla_not_external_legal_opinion_phase_1444"
)
GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN: str = (
    "gap_7_cla_milestone_complete_phase_1444"
)
GAP_7_PROVISIONAL_PATENT_DEFERRED_PHASE_1444_TOKEN: str = (
    "gap_7_provisional_patent_deferred_external_action_phase_1444"
)
GAP_7_TRADEMARK_DEFERRED_PHASE_1444_TOKEN: str = (
    "gap_7_trademark_deferred_external_action_phase_1444"
)
GAP_7_NOT_FULLY_CLOSED_PHASE_1444_TOKEN: str = (
    "gap_7_not_fully_closed_external_actions_pending_phase_1444"
)

PHASE_1444_CLA_GOVERNANCE_TOKENS: tuple[str, ...] = (
    CLA_TEXT_FINALIZED_PHASE_1444_TOKEN,
    CLA_GOVERNANCE_POLICY_COMMITTED_PHASE_1444_TOKEN,
    CLA_NOT_EXTERNAL_LEGAL_OPINION_PHASE_1444_TOKEN,
    GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN,
    GAP_7_PROVISIONAL_PATENT_DEFERRED_PHASE_1444_TOKEN,
    GAP_7_TRADEMARK_DEFERRED_PHASE_1444_TOKEN,
    GAP_7_NOT_FULLY_CLOSED_PHASE_1444_TOKEN,
)

__all__ = (
    "CLA_TEXT_FINALIZED_PHASE_1444_TOKEN",
    "CLA_GOVERNANCE_POLICY_COMMITTED_PHASE_1444_TOKEN",
    "CLA_NOT_EXTERNAL_LEGAL_OPINION_PHASE_1444_TOKEN",
    "GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN",
    "GAP_7_PROVISIONAL_PATENT_DEFERRED_PHASE_1444_TOKEN",
    "GAP_7_TRADEMARK_DEFERRED_PHASE_1444_TOKEN",
    "GAP_7_NOT_FULLY_CLOSED_PHASE_1444_TOKEN",
    "PHASE_1444_CLA_GOVERNANCE_TOKENS",
)
