# SPDX-License-Identifier: AGPL-3.0-only
"""Phase 1445 Gap 7 partial-closure status tokens."""

from __future__ import annotations

from ilc_core.rc.cla_governance_status import (
    CLA_TEXT_FINALIZED_PHASE_1444_TOKEN,
    GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN,
)
from ilc_core.rc.license_header_audit_phase_1443 import (
    AGPL_LICENSE_HEADER_AUDIT_COMPLETE_PHASE_1443_TOKEN,
    PUBLIC_SOURCE_ALLOWLIST_EXECUTION_COMPLETE_PHASE_1443_TOKEN,
)


GAP_7_INTERNAL_MILESTONES_COMPLETE_PHASE_1445_TOKEN = (
    "gap_7_internal_milestones_complete_phase_1445"
)
GAP_7_PARTIALLY_CLOSED_PHASE_1445_TOKEN = "gap_7_partially_closed_phase_1445"
PROVISIONAL_PATENT_DEFERRED_EXTERNAL_COUNSEL_REQUIRED_PHASE_1445_TOKEN = (
    "provisional_patent_deferred_external_counsel_required_phase_1445"
)
TRADEMARK_REGISTRATION_DEFERRED_EXTERNAL_ACTION_REQUIRED_PHASE_1445_TOKEN = (
    "trademark_registration_deferred_external_action_required_phase_1445"
)
GAP_7_NOT_FULLY_CLOSED_PHASE_1445_TOKEN = "gap_7_not_fully_closed_phase_1445"

GAP_7_CLOSURE_STATUS = {
    "agpl_license_headers": "complete_phase_1443",
    "cla_text": "complete_phase_1444",
    "provisional_patent_application": "deferred_external_counsel_required",
    "trademark_registration": "deferred_external_action_required",
    "gap_7_fully_closed": False,
}

PHASE_1445_GAP_7_CLOSURE_TOKENS: tuple[str, ...] = (
    GAP_7_INTERNAL_MILESTONES_COMPLETE_PHASE_1445_TOKEN,
    GAP_7_PARTIALLY_CLOSED_PHASE_1445_TOKEN,
    PROVISIONAL_PATENT_DEFERRED_EXTERNAL_COUNSEL_REQUIRED_PHASE_1445_TOKEN,
    TRADEMARK_REGISTRATION_DEFERRED_EXTERNAL_ACTION_REQUIRED_PHASE_1445_TOKEN,
    GAP_7_NOT_FULLY_CLOSED_PHASE_1445_TOKEN,
)

PHASE_1445_GAP_7_INPUT_DEPENDENCY_TOKENS: tuple[str, ...] = (
    AGPL_LICENSE_HEADER_AUDIT_COMPLETE_PHASE_1443_TOKEN,
    PUBLIC_SOURCE_ALLOWLIST_EXECUTION_COMPLETE_PHASE_1443_TOKEN,
    CLA_TEXT_FINALIZED_PHASE_1444_TOKEN,
    GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN,
)

__all__ = (
    "AGPL_LICENSE_HEADER_AUDIT_COMPLETE_PHASE_1443_TOKEN",
    "PUBLIC_SOURCE_ALLOWLIST_EXECUTION_COMPLETE_PHASE_1443_TOKEN",
    "CLA_TEXT_FINALIZED_PHASE_1444_TOKEN",
    "GAP_7_CLA_MILESTONE_COMPLETE_PHASE_1444_TOKEN",
    "GAP_7_INTERNAL_MILESTONES_COMPLETE_PHASE_1445_TOKEN",
    "GAP_7_PARTIALLY_CLOSED_PHASE_1445_TOKEN",
    "PROVISIONAL_PATENT_DEFERRED_EXTERNAL_COUNSEL_REQUIRED_PHASE_1445_TOKEN",
    "TRADEMARK_REGISTRATION_DEFERRED_EXTERNAL_ACTION_REQUIRED_PHASE_1445_TOKEN",
    "GAP_7_NOT_FULLY_CLOSED_PHASE_1445_TOKEN",
    "GAP_7_CLOSURE_STATUS",
    "PHASE_1445_GAP_7_CLOSURE_TOKENS",
    "PHASE_1445_GAP_7_INPUT_DEPENDENCY_TOKENS",
)
